### ISSUE TITLE
Add more fields

### ISSUE THREAD

**Issue by denisa84** [technodelight/magento_custom_reports_example#4]
Hello! Thank you very much for your extension!
I have one extra question regarding adding more fields.
Where in the collection can I add extra fields? I need to join with catalog_product_entity & eav_attribute and catalog_product_entity_varchar to get some data for reports.

Thanks.

**Comment by technodelight** [comment]
@denisa84 You're welcome. I don't know if your problem already solved or not, but let's keep this here for the history.
You can add extra columns to display within the `My_Reports_Block_Adminhtml_Report_Grid` class in the method `_prepareColumns`. Obviously, you need data there to display. This could be achieved easily if you create your own resource class and implement the required aggregation there. You can see how I done this in my example class here: `My_Reports_Model_Mysql4_Report_Collection`.
Ping me with mentioning me if you have more questions ;)
